services:
  luabla_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data
    ports:
      - "8701:5432"
    environment:
      POSTGRES_DB: Luabla_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mach1029
    networks:
      - luabla-network

  luabla:
    build: .
    command: sh -c "python manage.py makemigrations Authentication --noinput && python manage.py migrate Authentication --noinput && python manage.py makemigrations --noinput && python manage.py makemigrations Community --noinput && python manage.py makemigrations Chinese --noinput && python manage.py makemigrations English --noinput && python manage.py makemigrations Profile --noinput && python manage.py migrate --noinput && python manage.py makemigrations Welcome --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8700"
    volumes:
      - .:/app
    ports:
      - "8700:8700"
    depends_on:
      - luabla_db
    environment:
      - DEBUG=1
      - DB_NAME=Luabla_DB
      - DB_USER=postgres
      - DB_PASSWORD=mach1029
      - DB_HOST=luabla_db
      - DB_PORT=5432
    networks:
      - luabla-network

volumes:
  postgres_data:

networks:
  luabla-network:
    driver: bridge
