# Generated by Django 5.0.6 on 2024-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='agree_to_tems',
            new_name='agree_to_terms',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
    ]
