# Generated by Django 5.0.6 on 2024-07-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_rename_agree_to_tems_user_agree_to_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
