# Generated by Django 5.0.6 on 2024-07-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
