# Generated by Django 5.0.6 on 2024-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
