# Generated by Django 5.0.6 on 2024-07-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='english_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5),
        ),
    ]
